### ISSUE TITLE
Attaching Error ./ikbdop.sh attach

### ISSUE THREAD

**Issue by leanwell** [anitaggu/ikbdop#1]
Detach feature is working but the attach doesn't, see the terminal result below.

leanwell@bu30-satellite:~/Downloads/2/ikbdop-main$ ./ikbdop.sh attach
awk: cmd. line:7: warning: escape sequence `\[' treated as plain `['
awk: cmd. line:7: warning: escape sequence `\(' treated as plain `('
awk: cmd. line:8: warning: escape sequence `\)' treated as plain `)'
awk: cmd. line:8: warning: escape sequence `\]' treated as plain `]'
awk: cmd. line:7: (FILENAME=- FNR=8) fatal: invalid regexp: Unmatched ( or \(: /.*[slave[[:space:]]*keyboard[[:space:]]*(/
Executing command: xinput reattach 13 2
X Error of failed request:  XI_BadDevice (invalid Device parameter)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  43 ()
  Device id in failed request: 0x17
  Serial number of failed request:  19
  Current serial number in output stream:  20

**Comment by anitaggu** [comment]
Thanks for this bug report -- which has been fixed in the latest release.
